package entities;
// Generated 11-jun-2018 22:41:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Dish generated by hbm2java
 */
public class Dish  implements java.io.Serializable {


     private String name;
     private Restaurant restaurant;
     private String type;
     private BigDecimal price;
     private Set rates = new HashSet(0);

    public Dish() {
    }

	
    public Dish(String name, Restaurant restaurant, String type, BigDecimal price) {
        this.name = name;
        this.restaurant = restaurant;
        this.type = type;
        this.price = price;
    }
    public Dish(String name, Restaurant restaurant, String type, BigDecimal price, Set rates) {
       this.name = name;
       this.restaurant = restaurant;
       this.type = type;
       this.price = price;
       this.rates = rates;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Set getRates() {
        return this.rates;
    }
    
    public void setRates(Set rates) {
        this.rates = rates;
    }




}


