package entities;
// Generated 11-jun-2018 22:41:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private String name;
     private String city;
     private String specialty;
     private Set dishes = new HashSet(0);

    public Restaurant() {
    }

	
    public Restaurant(String name, String city, String specialty) {
        this.name = name;
        this.city = city;
        this.specialty = specialty;
    }
    public Restaurant(String name, String city, String specialty, Set dishes) {
       this.name = name;
       this.city = city;
       this.specialty = specialty;
       this.dishes = dishes;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getSpecialty() {
        return this.specialty;
    }
    
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }
    public Set getDishes() {
        return this.dishes;
    }
    
    public void setDishes(Set dishes) {
        this.dishes = dishes;
    }




}


