package entities;
// Generated 11-jun-2018 22:41:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;


@NamedQueries({
    @NamedQuery(name = "User.findAll", query = "SELECT u FROM User u"),
    @NamedQuery(name = "User.findByUsername", query = "SELECT u FROM User u WHERE u.username = :username")
})

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String city;
     private String name;
     private String surname;
     private int type;
     private Set rates = new HashSet(0);

    public User() {
    }

	
    public User(String username, String password, String city, String name, int type) {
        this.username = username;
        this.password = password;
        this.city = city;
        this.name = name;
        this.type = type;
    }
    public User(String username, String password, String city, String name, String surname, int type, Set rates) {
       this.username = username;
       this.password = password;
       this.city = city;
       this.name = name;
       this.surname = surname;
       this.type = type;
       this.rates = rates;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getRates() {
        return this.rates;
    }
    
    public void setRates(Set rates) {
        this.rates = rates;
    }
}


